### ISSUE TITLE
Links within <Note> elements are hard to see

### ISSUE THREAD

**Issue by Return180bpm** [excaliburjs/excaliburjs.github.io#116]
This applies only to the `info` variant of the Note element (which is also the default that comes out when one simply writes `<Note>`).  

The default theme of Semantic UI that is being used now gives us a blueish box with blue text and blue links without any decoration.  

Demo. I can't tell at a glance if there are any links here.
![Screenshot 2021-10-30 at 20 54 58](https://user-images.githubusercontent.com/59713582/139555349-0a844098-34f7-4c63-9130-06fb7e07031c.png)

PR coming.

**Comment by kamranayub** [comment]
thank you @Return180bpm !
