### ISSUE TITLE
Search box on Edge docs not working

### ISSUE THREAD

**Issue by jedeen** [excaliburjs/excaliburjs.github.io#15]
Previously, typing while on the API Documentation page would begin filling in the search box at the top. This functionality no longer works on the [Edge documentation](https://excaliburjs.com/docs/api/edge/index.html)

browsers: Chrome 57.0.2987.133, Firefox 53.0.2

Note: the search box still works on the [latest stable](https://excaliburjs.com/docs/api/v0.10.0/) documentation page (currently 0.10.0).

**Comment by kamranayub** [comment]
I think it's due to changes in the template, I fixed it previously

**Comment by jedeen** [comment]
Update: the search box does not appear to be working on the "latest stable" page anymore, either.

**Comment by kamranayub** [comment]
Fixed in https://github.com/excaliburjs/Excalibur/pull/836
