### ISSUE TITLE
Getting Started docs bad info

### ISSUE THREAD

**Issue by marcosmarp** [excaliburjs/excaliburjs.github.io#223]
I already seen this issue [here](https://github.com/excaliburjs/Excalibur/pull/987) but it's back again.

After creating the ball, the docs say `The ball will now bounce off of the paddle, but does not bounce with the side of the screen. To fix that, let’s take advantage of the postupdate event.`

This isn't true, the bouncing won't actually work until we configure the collisionstart/collisionend events on the last steps.

**Comment by eonarheim** [comment]
@marcosmarp Thanks for the issue, I'll take a look and correct the documentation

**Comment by eonarheim** [comment]
Updated!
