### ISSUE TITLE
Scene lifecycle image is broken

### ISSUE THREAD

**Issue by benlakey** [excaliburjs/excaliburjs.github.io#24]
There is a scene lifecycle image that should appear on this page:
https://excaliburjs.com/docs/api/v0.18.0/classes/_scene_.scene.html

That image is currently broken as of 9/18. I found a copy of the image within this issue if it needs to be recovered: https://github.com/excaliburjs/excaliburjs.github.io/issues/17

I've also attached it here just in case:

![lifecycle](https://user-images.githubusercontent.com/712322/45727642-76995f80-bb79-11e8-88ac-1e6e85317215.png)

**Comment by kamranayub** [comment]
Thanks @benlakey, should be fixed in https://github.com/excaliburjs/excaliburjs.github.io/commit/a31e84ec128bc7e809b41445941a9f2b45cbe05c
