### ISSUE TITLE
Many ludum games that are linked to on gallery page are private repos

### ISSUE THREAD

**Issue by alanag13** [excaliburjs/excaliburjs.github.io#28]
If we intend the source to be visible, we should make these public. Otherwise we should remove the links to the source.

**Comment by jedeen** [comment]
These repositories were marked private to remove any implication that they should be used as resources or examples of best practices for developing games with Excalibur. Perhaps we should remove the links?

**Comment by jedeen** [comment]
The game jam repositories have been marked in their descriptions and readme files with a warning against using them as examples. Readers are instead recommended to use the list of official Excalibur samples as reference material.
