### ISSUE TITLE
The "Ask a Question" Link in the footer is missing a URL

### ISSUE THREAD

**Issue by jedeen** [excaliburjs/excaliburjs.github.io#36]
Previously, the "Ask a Question" link under the "Get Involved" section in the footer linked to the [Excalibur.js google group](https://groups.google.com/forum/#!forum/excaliburjs). On the current build of the live site, there is no `href` attribute in the anchor tag.

![image](https://user-images.githubusercontent.com/675840/65771878-c3a20100-e0fe-11e9-9cbb-ffe8f75736ac.png)

![image](https://user-images.githubusercontent.com/675840/65771913-d3b9e080-e0fe-11e9-95cd-90186a4ef3d1.png)

**Comment by kamranayub** [comment]
Thanks, should be fixed now.
