### ISSUE TITLE
ExcaliburJS Docs' 'Welcome' page's first paragraph doesn't make sense

### ISSUE THREAD

**Issue by proplayer919** [excaliburjs/excaliburjs.github.io#373]
# ExcaliburJS Docs' 'Welcome' page's first paragraph doesn't make sense

> Excalibur is a free [open source](https://github.com/excaliburjs/Excalibur) 2D game engine written in [TypeScript](https://www.typescriptlang.org/) for the web written in TypeScript for making 2D games in HTML5 canvas.

This (above) doesn't make sense ("... written in TypeScript for the web written in TypeScript ..."). In this extract "written in TypeScript" appears twice.

**Comment by esonarhe** [comment]
@proplayer919 Good find! We'll fix that up

**Comment by eonarheim** [comment]
Fixed in [54b6ac0](https://github.com/excaliburjs/excaliburjs.github.io/commit/54b6ac00e8709a43f1580ecd6ccc753ab1b6610c)

@proplayer919 Thanks!

**Comment by eonarheim** [comment]
It should be deployed as soon as the build finishes
