### ISSUE TITLE
A few small bugs

### ISSUE THREAD

**Issue by ebutleratlassian** [excaliburjs/excaliburjs.github.io#38]
Both bugs are small and I have reproduced them both here --
https://codesandbox.io/s/excaliburjs-reproduction-01-pezj9

The first bug might be more of a clarification issue with typings...
the typings for `new ex.Scene` indicate that it requires an Engine object to be passed in, yet it actually does not. Why is this? I see that the argument is labeled in the Typescript idiom which indicates an unused variable (_leading underscore_). 

The second bug is that the Label constructor which I am using, non-object configuration, accepts a string for the 4th argument **fontFamily** which the documentation indicates (https://github.com/excaliburjs/Excalibur/blame/master/src/engine/Docs/Labels.md#L11) can be a font size and a font family yet whenever I use a font size there like '48px Arial' then the entire fontFamily seems unapplied.

Thanks for your time, awesome library! :)

**Comment by eonarheim** [comment]
@ebutleratlassian Thanks for posting! Both are definitely not ideal issues.

I've created 2 bugs for this on the main repo for tracking:

* Confusing Scene constructor: https://github.com/excaliburjs/Excalibur/issues/1363

* Label font family issue: https://github.com/excaliburjs/Excalibur/issues/1364 

I'll close this issue and we can track progress there! Please let me know if you have any other ideas/feedback about Excalibur!
