### ISSUE TITLE
Docs Site v2

### ISSUE THREAD

**Issue by kamranayub** [excaliburjs/excaliburjs.github.io#383]
Working issue for thinking about the next version of the docs site.

## Context

The current website is built on a custom Gatsby.js site, with support for MDX and API reference links (using a custom plugin). It is also built with Semantic UI styles.

## Objective

We would like to better organize the documentation site and make it more example-rich, along with a refreshed homepage and onboarding experience.

## Goals

- Accessible and mobile-friendly documentation
- Organize docs under the [Diátaxis system](https://diataxis.fr/)
- Frictionless and contributor-friendly DX
- Simpler CI/CD workflow with a smoother Typedoc integration
- Integrated with API reference docs
- Integration of compiled, interactive examples
- Product analytics to understand usage patterns
- Support for natively-integrated interactive tutorials

## Non-Goals

- Restricted editing access
- Complicated local DX
- Expensive hosting
- Maintenance-heavy upgrades

## Pain Points

Here's what sucks about the current implementation:

- Typedoc upgrades are totally manual and need to be coordinated across the core repo and this docs repo
- The docs area is entirely custom and isn't on parity accessibility-wise with something like Docusaurus
- API docs are separately built in a custom workflow and requires convoluted orchestration scripts
- Creating examples is done in the core repo with Storybook, or manually with snippets in this repo (it's not unified or consistent)
- Managing package dependency upgrades is annoying

## Ideas

- [Docusaurus ](https://docusaurus.io/) maintains React support with MDX
  - Typedoc through [docusaurus-plugin-typedoc-api](https://github.com/milesj/docusaurus-plugin-typedoc-api) ([example](https://boostlib.dev/api))
  - Supports API docs [linking](https://github.com/milesj/docusaurus-plugin-typedoc-api/blob/master/packages/plugin/README.md#linking)
  - Supports [Posthog](https://github.com/PostHog/posthog-docusaurus) for analytics
- We could update the theme to be based off https://github.com/hasura/gatsby-gitbook-starter
  - Worth noting: Hasura switched to Docusaurus v2 😄 
- We could switch to hosting on something like [Mintlify](https://mintlify.com)
  - But this will (likely) restrict who can contribute.
  - And we are at the mercy of the platform
  - GitBooks is free for OSS teams but it may not be as customizable as we'd like

## Decisions

1. What framework or library should be used to build the docs?
2. What provider should be used to host the site?
3. Should we consolidate docs into the core [excalibur](excaliburjs/excalibur) repo?

## Related

https://github.com/excaliburjs/Excalibur/discussions/2770

**Comment by kamranayub** [comment]
## Proposed Solution

The two closest contenders are going to be maintaining a custom Gatsby.js solution, or migrating to Docusaurus v2. I am heavily leaning towards the latter because it ticks all the boxes, _including_ API linking/Typedoc support through a plugin. It would lessen my own personal maintenance burden of custom plugins. Docusaurus gives us all the flexibility we need to add other pages, along with providing a stellar docs experience.

No matter the approach, I do not see any templates/plugins for building step-wise interactive tutorials like Storybook Tutorials or Cypress Guides (both of those are custom-built), nor has anyone created a Docusaurus plugin for something like [Medusa's Recipes or learning path experience](https://kamranayub.com/developer-waypoints-2-learning-paths/).

**Comment by eonarheim** [comment]
@kamranayub I'm 100% on board with the proposal.

I think cloudflare pages is worth a try, I think there are a lot of advantages merging docs into the main repo as you say. It definitely feels like it's worth it considering the drift we have to deal with.

Another advantage of doing a new thing in the main repo, is we can do side by side deployments of gh pages and cloudflare until we are ready to cutover DNS.

cc @chrisk-7777
