### ISSUE TITLE
outdated JSFiddle on Getting Started page

### ISSUE THREAD

**Issue by StevenClontz** [excaliburjs/excaliburjs.github.io#51]
The JSFiddle at the bottom of https://excaliburjs.com/docs/getting-started doesn't match with the docs, and seems to use an outdated API (e.g. uses `this.getWidth()` rather than `this.width`).

**Comment by eonarheim** [comment]
Thanks for pointing this out, I think we'll want to move this to a
stackblitz or a codesandbox

**Comment by eonarheim** [comment]
@StevenClontz the new docs are in process of deploying, here is an updated codesandbox 

https://codesandbox.io/s/sample-breakout-7tvfk?file=/src/main.ts
