### ISSUE TITLE
Responsive issues

### ISSUE THREAD

**Issue by muirch** [excaliburjs/excaliburjs.github.io#61]
There is issues with navigation on index page and docs. 
Tested on mobile and desktop browsers.

### Index page:
How it looks like on iPhone X: https://i.imgur.com/whYyOJQ.png
As you can see, there is some problems with navigation bar. 

Common solution: just add breakpoint for devices with screen < 728px with flex properties like flex-direction: column. Also there is need for removing 'floated right' classes.

### Docs
Docs have same issues like main page: top nav bar and sidebar on mobile devices are broken.
Screenshot: https://i.imgur.com/HfUrAYH.png

I suggest hide sidebar by default and add button that triggers hide/close events for mobile devices. 

Also there is problems with info messages: https://i.imgur.com/q4z3mpH.png

**Comment by Shofol** [comment]
@kamranayub, Can I work on this issue?

**Comment by kamranayub** [comment]
@Shofol go for it!

**Comment by kamranayub** [comment]
Thanks @muirch, all fixed up.

## homepage

![image](https://user-images.githubusercontent.com/563819/119926730-862df080-bf3d-11eb-8be6-d2de4a6b71a2.png)

## Docs nav

![image](https://user-images.githubusercontent.com/563819/119926704-79a99800-bf3d-11eb-9cce-25b01e05add2.png)

## info with code with long strings

![image](https://user-images.githubusercontent.com/563819/119926686-71515d00-bf3d-11eb-9604-af39ce5560eb.png)
